Algoritmo "Creuza02"
// Disciplina  :  [Linguagem e Logica de Programacao] 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/01/2020
Var
// Seção de Declarações das variáveis 
    reais ,dolares: Real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("quantos reais eu tenho?? R$")
     leia(reais)
     dolares <- reais/2.2
     escreva("Posso ter US$", dolares)
Fimalgoritmo