Algoritmo "contador 1 a 10"
// Disciplina  :  [Linguagem e Logica de Programacao] 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/02/2020
Var
// Seção de Declarações das variáveis 
 c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 para c <- 10 ate 1 passo -1 faca
  escreval(c)
 fimPara
Fimalgoritmo