Algoritmo "Creuza03"
// Disciplina  :  [Linguagem e Logica de Programacao] 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/01/2020
Var
// Seção de Declarações das variáveis
   F, C: Real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Qual é a temperatura aqui??")
  leia(F)
  C <- (F- 32) / 1.8
  escreva("No Brasil estaria", C)
Fimalgoritmo