Algoritmo "combinaçoes"
// Disciplina  :  [Linguagem e Logica de Programacao] 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/02/2020
Var
// Seção de Declarações das variáveis 
 c1, c2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    para c1 := 1 ate 2 faca
     para c2 := 1 ate 3 faca
      escreval (c1, c2)
     fimPara
    fimPara
Fimalgoritmo